name             'ruby-bits'
maintainer       'BlackBits'
maintainer_email 'anton@blackbits.pro'
license          'All rights reserved'
description      'configures ruby'
version          '0.1.0'

depends 'git'
depends 'rbenv'
depends 'imagemagick'
depends 'postgresql'
